services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3G\Hubspot\Command\SynchronizeContactsCommand:
        tags:
            - name: 'hubspot.synchronizeContacts'
              command: 'hubspot:contactsync'
              schedulable: true
