name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^8.7, ^9.5, ^10.4]
        php: ['7.2', '7.3', '7.4']

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: CGL
        run: composer t3g:cgl

      - name: Lint PHP
        run: composer t3g:test:php:lint

      - name: Unit Tests
        run: composer t3g:test:php:unit
